- hosts: S2
  become: yes
  tasks:

  - name: copy eth0 conf files
    copy: 
      src: S2/ifcfg-eth0
      dest: /etc/sysconfig/network-scripts/

  - name: copy vlan102 conf files
    copy: 
      src: S2/ifcfg-vlan102
      dest: /etc/sysconfig/network-scripts/

  - name: restart network
    service:
      name: network
      state: restarted
      