- hosts: C1 
  become: yes
  tasks:

  - name: copy eth0 conf files
    copy: 
      src: C1/ifcfg-eth0
      dest: /etc/sysconfig/network-scripts/

  - name: copy vlan101 conf files
    copy: 
      src: C1/ifcfg-vlan101
      dest: /etc/sysconfig/network-scripts/

  - name: restart network
    service:
      name: network
      state: restarted
      